spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      # For testing purposes - THIS CAN'T BE USED IN PROD
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://alexandre-delta.vercel.app"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      
        webflux:
          routes:
            ## User Service Route
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/auth/api/**, /profile/api/**, /city/api/**, /address/api/**, /paymentmethod/api/**

            ## Order Service Route
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/api/**, /item/api/**

            ## Inventory Service Route
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/api/**

            ## Payment Service Route
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment/api/**

            ## Delivery Service Route
            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/delivery/api/**, /delivery-city/api/**, /delivery-company/api/**

server:
  port: 4000
  ## THIS SHOULDN'E BE USED IN PRODUCTION
  ssl:
    enabled: true
    key-store: file:/app/api-gateway/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
