spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.alexandre.event"
      group-id: notification-service

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${FROM_EMAIL}

server:
  port: 8084