spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/alexandre_order_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.alexandre.orderservice.event.NotificationEvent
    template:
      default-topic: "notification"

server:
  port: 8082