spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/alexandre_payment_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.alexandre.notificationservice.event.NotificationEvent
      group-id: notificationId

    template:
      default-topic: "payment"


server:
  port: 8085

stripe:
#  secret-key: ${STRIPE_API_KEY}
  success-url: http://localhost:8085/payment/api/v1/success
  cancel-url: http://localhost:8085/payment/api/v1/cancel