spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.alexandre.notificationservice.event.NotificationEvent
      group-id: notificationId

    template:
      default-topic: "payment"


server:
  port: 8085