spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alexandre_user_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  url: http://localhost:8080/
  admin-username: ${KC_ADMIN_USERNAME:alex}
  admin-password: ${KC_ADMIN_PASSWORD:AlexAdmin}
  realm: Alexandre
  client-id: public-client
  client-secret: aa
